services:
  postgres:
    image: postgres:16
    container_name: smart-ebike-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-smart_ebike}
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_password}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: smart-ebike-pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: "False"
    ports:
      - "5050:80"

  api:
    build:
      context: ../backend
    container_name: smart-ebike-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgresql://${POSTGRES_USER:-app_user}:${POSTGRES_PASSWORD:-app_password}@postgres:5432/${POSTGRES_DB:-smart_ebike}
      JWT_SECRET: ${JWT_SECRET:-dev_secret}
      ADMIN_SETUP_TOKEN: ${ADMIN_SETUP_TOKEN:-setup123}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:8080}
    ports:
      - "4000:4000"

  web:
    build:
      context: ../frontend
    container_name: smart-ebike-web
    depends_on:
      - api
    ports:
      - "8080:80"

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: smart-ebike-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:11.1.0
    container_name: smart-ebike-grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  pgdata:                                   
    external: true
    name: smart-ebike_postgres_data
  grafana_data: {}
